name: Codegen
on:
  pull_request:
    paths:
    - '**.go'

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: run codegen
      run: GOPATH=$(go env GOPATH) make codegen

    - name: validate codegen
      run: tests/scripts/validate_modified_files.sh codegen

